area_demand/urls.py
from django.conf.urls import url
from area_demand import views

urlpatterns = [
    url(r'^index$', views.index, name='index'),  # 首页
    url(r'^areas$', views.areas, name='area'),  # 地址首页
    url(r'^prov$', views.prov),  # 获取所有身份的信息
    url(r'^city/(?P<id>\d+)$', views.city),  # 获取所有城市
    url(r'^dis/(?P<id>\d+)$', views.city),  # 获取所有城市
]

choose_area/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('area_demand.urls', namespace='zw_areas'))
]

area_demand/models.py
from django.db import models


# Create your models here.
# 自定义模型管理器类
class AreaInfoManager(models.Manager):
    def my_all(self):
        return self.all()


class AreaInfo(models.Model):
    atitle = models.CharField(max_length=64)
    aParent = models.ForeignKey('self', null=True, blank=True)

    class Meta:
        db_table = 'areas'

    def __str__(self):
        return self.atitle

    # 调用自定义管理器类
    areas = AreaInfoManager()

area_demand/views.py
from django.shortcuts import render
from area_demand.models import AreaInfo
from django.http import JsonResponse,HttpResponse
# Create your views here.
# /index
def index(request):
    return render(request, 'area_demand/index.html')

# /areas
def areas(request):
    areas_addr = AreaInfo.areas.my_all()
    return render(request, 'area_demand/areas.html', {'areas_addr': areas_addr})

# /prov     获取所有省份信息
def prov(request):
    provinces = AreaInfo.areas.filter(aParent__isnull=True)
    prov_arr = []
    for province in provinces:
        prov_arr.append((province.id, province.atitle))
    return JsonResponse({'data': prov_arr})


# /city
def city(request, id):
    city_arr = []
    cities = AreaInfo.areas.filter(aParent_id=id)
    for city_area in cities:
        city_arr.append((city_area.id, city_area.atitle))
    return JsonResponse({'data': city_arr})

templates/area_demand/areas.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static from staticfiles %}
    {% load filters %}
    <title>省市县查询</title>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(function () {
            $.get('/prov', function (data) {
                console.log(data.data)
                var prov_data = data.data;
                var prov = $('#prov');
                for(var i=0; i<prov_data.length; i++) {
                    prov.append('<option value="'+ prov_data[i][0] +'">' + prov_data[i][1] + '</option>')
                }
            })

            $('#prov').change(function () {
                var id = $(this).val()
                $.get('/city/'+id, function (data) {
                    var city_data = data.data;
                    var city = $('#city');
                    city.empty().append('<option value="">---请选择市---</option>')
                    $("#dis").empty().append('<option value="">---请选择县---</option>')
                    $.each(city_data, function (index, item) {
                        city.append('<option value="'+ item[0] +'">' + item[1] + '</option>')
                    })
                })
            })

            $("#city").change(function () {
                var id = $(this).val()

                $.get('/dis/'+id, function (data) {
                    console.log(data.data)
                    var dis_data = data.data
                    var dis = $('#dis')
                    dis.empty().append('<option value="">---请选择县---</option>')
                    $.each(dis_data, function (index, element) {
                        dis.append('<option value=">' + element[0] + '">' + element[1] + '</option>')
                    })
                })
            })
        })
    </script>

</head>
<body>
<select name="" id="prov">
    <option value="">---请选择省---</option>
</select>
<select name="" id="city">
    <option value="">---请选择市---</option>
</select>
<select name="" id="dis">
    <option value="">---请选择县---</option>
</select>


{# 自定义过滤器 #}
<ul>
    {% for area in areas_addr %}
        {% if area.id|mod %}
            <li>{{ area }}</li>
        {% endif %}
    {% endfor %}
</ul>
</body>
</html>

templates/area_demand/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href="{% url 'zw_areas:area' %}">测试</a>
</body>
</html>